"""Internal utilities for py-webdav."""

from .client import Client, discover_context_url
from .elements import (
    NAMESPACE,
    CurrentUserPrincipal,
    DisplayName,
    Error,
    GetContentLength,
    GetContentType,
    GetETag,
    GetLastModified,
    Href,
    Location,
    MultiStatus,
    PropertyUpdate,
    PropFind,
    PropStat,
    ResourceType,
    Response,
    Status,
    SyncCollectionQuery,
    new_error_response,
    new_ok_response,
)
from .internal import (
    Depth,
    HrefError,
    HTTPError,
    depth_to_string,
    format_overwrite,
    http_error_from_error,
    http_errorf,
    is_not_found,
    parse_depth,
    parse_overwrite,
)
from .server import Backend, Handler, serve_error, serve_multistatus, serve_xml

__all__ = [
    # client
    "Client",
    "discover_context_url",
    # elements
    "NAMESPACE",
    "CurrentUserPrincipal",
    "DisplayName",
    "Error",
    "GetContentLength",
    "GetContentType",
    "GetETag",
    "GetLastModified",
    "Href",
    "Location",
    "MultiStatus",
    "PropFind",
    "PropStat",
    "PropertyUpdate",
    "Response",
    "ResourceType",
    "Status",
    "SyncCollectionQuery",
    "new_error_response",
    "new_ok_response",
    # internal
    "Depth",
    "HrefError",
    "HTTPError",
    "depth_to_string",
    "format_overwrite",
    "http_error_from_error",
    "http_errorf",
    "is_not_found",
    "parse_depth",
    "parse_overwrite",
    # server
    "Backend",
    "Handler",
    "serve_error",
    "serve_multistatus",
    "serve_xml",
]
