{
    "openapi": "3.0.1",
    "info": {
        "title": "IN-FORM API",
        "description": "This document describes IN-FORM API providing access to the IN-FORM's data. API is build basis on REST architecture. Access to the resources is made by using one of possible request presented below.",
        "contact": {},
        "version": "v1"
    },
    "servers": [
        {
            "url": "https://testapi.in-software.com/v1/"
        }
    ],
    "security": [
        {
            "oAuth2": []
        }
    ],
    "tags": [
        {
            "name": "documentation",
            "description": "Access to openApi documentation"
        },
        {
            "name": "licenses",
            "description": "Basic informations about licence."
        },
        {
            "name": "authorization",
            "description": "Methods needed for authorization operation."
        },
        {
            "name": "companies",
            "description": "Access to IN-FORM companies resources."
        },
        {
            "name": "search",
            "description": "Searching in multiple resurces kinds in IN-FORM."
        },
        {
            "name": "employees",
            "description": "Access to IN-FORM's employees resources."
        },
        {
            "name": "equipment",
            "description": "Access to IN-FORM's equipment resources."
        },
        {
            "name": "mailboxes",
            "description": "Access to IN-FORM's mailboxes resources."
        },
        {
            "name": "addresses",
            "description": "Access to IN-FORM's addresses resources."
        },
        {
            "name": "contacts",
            "description": "Access to IN-FORM's contacts resources."
        },
        {
            "name": "items",
            "description": "Access to IN-FORM's items resources."
        },
        {
            "name": "documents",
            "description": "Access to IN-FORM's documents resources."
        },
        {
            "name": "projects",
            "description": "Access to IN-FORM's projects resources."
        },
        {
            "name": "calendarEvents",
            "description": "Access to IN-FORM's calendar events."
        },
        {
            "name": "timeTracking",
            "description": "Access to IN-FORM's time tracking entries API."
        },
        {
            "name": "servicedObjects",
            "description": "Access to IN-FORM's serviced objects resources"
        },
        {
            "name": "attachments",
            "description": "Access to IN-FORM's attachments resources."
        },
        {
            "name": "reports",
            "description": "Access to IN-FORM's reports and statistics."
        },
        {
            "name": "printouts",
            "description": "Access to IN-FORM's printouts."
        },
        {
            "name": "globalSettings",
            "description": "Access to IN-FORM's global settings."
        },
        {
            "name": "settings",
            "description": "Access to IN-FORM's settings."
        },
        {
            "name": "system",
            "description": "Access to IN-FORM's system informations."
        }
    ],
    "paths": {
        "/companies/{company}/contacts": {
            "post": {
                "tags": [
                    "contacts"
                ],
                "summary": "postContact",
                "description": "Used to create a contact entry for an address.<br><br>Minimal IN-FORM version required: **2025.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "postContact",
                "security": [
                    {
                        "oAuth2": [
                            "api:contacts:write"
                        ]
                    }
                ],
                "x-minInformVersion": "2025.00"
            },
            "get": {
                "tags": [
                    "contacts"
                ],
                "summary": "getContacts",
                "description": "Used to get a list of contact entries for an address.<br><br>Minimal IN-FORM version required: **2025.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getContacts",
                "security": [
                    {
                        "oAuth2": [
                            "api:contacts:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2025.00"
            }
        },
        "/companies/{company}/contacts/{key}": {
            "get": {
                "tags": [
                    "contacts"
                ],
                "summary": "getContact",
                "description": "Used to get Contact data.<br><br>Minimal IN-FORM version required: **2025.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getContact",
                "security": [
                    {
                        "oAuth2": [
                            "api:contacts:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2025.00"
            },
            "patch": {
                "tags": [
                    "contacts"
                ],
                "summary": "patchContact",
                "description": "Used to update a contact entry.<br><br>Minimal IN-FORM version required: **2025.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "patchContact",
                "security": [
                    {
                        "oAuth2": [
                            "api:contacts:write"
                        ]
                    }
                ],
                "x-minInformVersion": "2025.00"
            }
        },
        "/globalSettings/calendarEvents": {
            "get": {
                "x-minInformVersion": "2023.50",
                "tags": [
                    "globalSettings"
                ],
                "summary": "getCalendarEventsSettings",
                "description": "Used to get global settings for calendar events.<br><br>Minimal IN-FORM version required: **2023.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getCalendarEventsSettings"
            }
        },
        "/calendarEventsOccurrences": {
            "get": {
                "tags": [
                    "calendarEvents"
                ],
                "summary": "getCalendarEventsOccurrences",
                "description": "Used to get a list of calendar events occurrences for specified owner. Both standard events and serial events occurrences will be returned.<br><br>Minimal IN-FORM version required: **2024.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getCalendarEventsOccurrences",
                "security": [
                    {
                        "oAuth2": [
                            "api:communicationSystem:readWrite"
                        ]
                    }
                ],
                "x-minInformVersion": "2024.00"
            }
        },
        "/calendarEvents": {
            "post": {
                "tags": [
                    "calendarEvents"
                ],
                "summary": "postCalendarEvent",
                "description": "Used to create a calendar event in IN-FORM.<br><br>Minimal IN-FORM version required: **2024.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "postCalendarEvent",
                "security": [
                    {
                        "oAuth2": [
                            "api:communicationSystem:readWrite"
                        ]
                    }
                ],
                "x-minInformVersion": "2024.00"
            }
        },
        "/calendarEvents/{key}": {
            "get": {
                "tags": [
                    "calendarEvents"
                ],
                "summary": "getCalendarEvent",
                "description": "Used to get data for specified calendar event.<br><br>Minimal IN-FORM version required: **2023.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getCalendarEvent",
                "security": [
                    {
                        "oAuth2": [
                            "api:communicationSystem:readWrite"
                        ]
                    }
                ],
                "x-minInformVersion": "2023.50"
            },
            "patch": {
                "tags": [
                    "calendarEvents"
                ],
                "summary": "patchCalendarEvent",
                "description": "Use this request to modify a calendar event.<br><br>Minimal IN-FORM version required: **2024.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "patchCalendarEvent",
                "security": [
                    {
                        "oAuth2": [
                            "api:communicationSystem:readWrite"
                        ]
                    }
                ],
                "x-minInformVersion": "2024.00"
            },
            "delete": {
                "tags": [
                    "calendarEvents"
                ],
                "summary": "deleteCalendarEvent",
                "description": "Use this request to delete a calendar event.<br><br>Minimal IN-FORM version required: **2024.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "deleteCalendarEvent",
                "security": [
                    {
                        "oAuth2": [
                            "api:communicationSystem:readWrite"
                        ]
                    }
                ],
                "x-minInformVersion": "2024.00"
            }
        },
        "/calendarEvents/{key}/occurrences/{occurrenceId}": {
            "get": {
                "tags": [
                    "calendarEvents"
                ],
                "summary": "getCalendarSerialEventOccurrence",
                "description": "Used to get data for an occurence of a serial calendar event.<br><br>Minimal IN-FORM version required: **2024.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getCalendarSerialEventOccurrence",
                "security": [
                    {
                        "oAuth2": [
                            "api:communicationSystem:readWrite"
                        ]
                    }
                ],
                "x-minInformVersion": "2024.00"
            },
            "patch": {
                "tags": [
                    "calendarEvents"
                ],
                "summary": "patchCalendarSerialEventOccurrence",
                "description": "Use this request to modify an occurence of a serial calendar event.<br><br>Minimal IN-FORM version required: **2024.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "patchCalendarSerialEventOccurrence",
                "security": [
                    {
                        "oAuth2": [
                            "api:communicationSystem:readWrite"
                        ]
                    }
                ],
                "x-minInformVersion": "2024.00"
            },
            "delete": {
                "tags": [
                    "calendarEvents"
                ],
                "summary": "deleteCalendarSerialEventOccurrence",
                "description": "Use this request to delete an occurence of a serial calendar event. Serial event occurrences cannot be moved to trash and are always deleted permanently.<br><br>Minimal IN-FORM version required: **2024.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "deleteCalendarSerialEventOccurrence",
                "security": [
                    {
                        "oAuth2": [
                            "api:communicationSystem:readWrite"
                        ]
                    }
                ],
                "x-minInformVersion": "2024.00"
            }
        },
        "/companies/{company}/printouts/prepare": {
            "post": {
                "tags": [
                    "printouts"
                ],
                "summary": "preparePrintout",
                "description": "Used to start preparing specified printout.<br>Returns ID of requested printout, which can be used in getPrintout request to download it.<br><br>Minimal IN-FORM version required: **2023.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "preparePrintout",
                "security": [
                    {
                        "oAuth2": []
                    }
                ],
                "x-minInformVersion": "2023.00"
            }
        },
        "/companies/{company}/printouts/results/{id}/state": {
            "get": {
                "tags": [
                    "printouts"
                ],
                "summary": "getPrintoutState",
                "description": "Used to get printout state, using ID returned from preparePrintout request.<br><br>Minimal IN-FORM version required: **2023.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getPrintoutState",
                "security": [
                    {
                        "oAuth2": []
                    }
                ],
                "x-minInformVersion": "2023.00"
            }
        },
        "/companies/{company}/printouts/results/{id}": {
            "get": {
                "tags": [
                    "printouts"
                ],
                "summary": "getPrintout",
                "description": "Used to get printout (in PDF format), using ID returned from preparePrintout request.<br><br>Minimal IN-FORM version required: **2023.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getPrintout",
                "security": [
                    {
                        "oAuth2": []
                    }
                ],
                "x-minInformVersion": "2023.00"
            }
        },
        "/companies/{company}/reports/invoicesBalance": {
            "get": {
                "tags": [
                    "reports"
                ],
                "summary": "getInvoiceBalanceReport",
                "description": "Used to get this months invoices balance report.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getInvoiceBalanceReport",
                "security": [
                    {
                        "oAuth2": [
                            "api:reports:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2022.50"
            }
        },
        "/companies/{company}/reports/workingTimeSummary": {
            "get": {
                "tags": [
                    "reports"
                ],
                "summary": "getTimeSummaryReport",
                "description": "Used to get this months employees working time summary report.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getTimeSummaryReport",
                "security": [
                    {
                        "oAuth2": [
                            "api:reports:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2022.50"
            }
        },
        "/companies": {
            "get": {
                "tags": [
                    "companies"
                ],
                "summary": "getCompanies",
                "description": "Use this request to get the list of companies in IN-FORM which user is allowed to work with.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getCompanies",
                "x-minInformVersion": "2022.50"
            }
        },
        "/companies/{company}": {
            "get": {
                "tags": [
                    "companies"
                ],
                "summary": "getCompany",
                "description": "Use this request to get informations about specified company in IN-FORM.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getCompany",
                "x-minInformVersion": "2022.50"
            }
        },
        "/companies/{company}/binaryData/{field}": {
            "get": {
                "tags": [
                    "companies"
                ],
                "summary": "getBinaryDataFromCompany",
                "description": "Use this endpoint to get efficiently the single, selected field, containing large data from specified company in IN-FORM as binary data.<br>It works faster, than **getCompany** request.<br><br>Minimal IN-FORM version required: **2024.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getBinaryDataFromCompany",
                "x-minInformVersion": "2024.00"
            }
        },
        "/employees": {
            "get": {
                "tags": [
                    "employees"
                ],
                "summary": "getEmployees",
                "description": "Use this request to get the list of employees in IN-FORM with their information.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getEmployees",
                "x-minInformVersion": "2022.50"
            }
        },
        "/employees/{key}": {
            "get": {
                "tags": [
                    "employees"
                ],
                "summary": "getEmployee",
                "description": "Use this request to get the informations about specified employee in IN-FORM.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getEmployee",
                "x-minInformVersion": "2022.50"
            },
            "patch": {
                "tags": [
                    "employees"
                ],
                "summary": "patchEmployee",
                "description": "Use this request to modify the informations about specified employee.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "patchEmployee",
                "x-minInformVersion": "2022.50"
            }
        },
        "/employees/{key}/binaryData/{field}": {
            "get": {
                "tags": [
                    "employees"
                ],
                "summary": "getBinaryDataFromEmployee",
                "description": "Use this endpoint to get efficiently the single, selected field, containing large data from specified employee as binary data.<br>It works faster, than **getEmployee** request.<br><br>Minimal IN-FORM version required: **2024.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getBinaryDataFromEmployee",
                "x-minInformVersion": "2024.00"
            },
            "patch": {
                "tags": [
                    "employees"
                ],
                "summary": "patchBinaryDataInEmployee",
                "description": "Use this endpoint to update efficiently the single, selected field, containing large data in specified employee as binary data.<br>It works faster, than **patchEmployee** request.<br><br>Minimal IN-FORM version required: **2024.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "patchBinaryDataInEmployee",
                "x-minInformVersion": "2024.00"
            }
        },
        "/equipment": {
            "get": {
                "tags": [
                    "equipment"
                ],
                "summary": "listEquipment",
                "description": "Use this request to get the list of equipment in IN-FORM.<br><br>Minimal IN-FORM version required: **2025.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "listEquipment",
                "x-minInformVersion": "2025.00"
            }
        },
        "/equipment/{key}": {
            "get": {
                "tags": [
                    "equipment"
                ],
                "summary": "getEquipment",
                "description": "Use this request to get the information about a specific equipment in IN-FORM.<br><br>Minimal IN-FORM version required: **2025.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getEquipment",
                "x-minInformVersion": "2025.00"
            }
        },
        "/mailboxes": {
            "get": {
                "tags": [
                    "mailboxes"
                ],
                "summary": "getMailboxes",
                "description": "Use this request to get the list of mailboxes in IN-FORM.<br><br>Minimal IN-FORM version required: **2025.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getMailboxes",
                "x-minInformVersion": "2025.00"
            }
        },
        "/mailboxes/{key}": {
            "get": {
                "tags": [
                    "mailboxes"
                ],
                "summary": "getMailbox",
                "description": "Use this request to get the information about a specific mailbox in IN-FORM.<br><br>Minimal IN-FORM version required: **2025.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getMailbox",
                "x-minInformVersion": "2025.00"
            }
        },
        "/companies/{company}/attachments": {
            "post": {
                "tags": [
                    "attachments"
                ],
                "summary": "uploadAttachment",
                "description": "Used to upload attachment file.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "uploadAttachment",
                "security": [
                    {
                        "oAuth2": [
                            "api:attachments:write"
                        ]
                    }
                ],
                "x-minInformVersion": "2022.50"
            },
            "get": {
                "tags": [
                    "attachments"
                ],
                "summary": "getAttachments",
                "description": "Used to get list of attachments metadata.<br>This request does not returns attachments as files.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getAttachments",
                "security": [
                    {
                        "oAuth2": [
                            "api:attachments:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2022.50"
            }
        },
        "/companies/{company}/attachments/{key}": {
            "get": {
                "tags": [
                    "attachments"
                ],
                "summary": "getAttachment",
                "description": "Used to get attachment's metadata.<br>This request does not returns attachment as files.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getAttachment",
                "security": [
                    {
                        "oAuth2": [
                            "api:attachments:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2022.50"
            },
            "delete": {
                "tags": [
                    "attachments"
                ],
                "summary": "deleteAttachment",
                "description": "Used to delete attachment.<br><br>Minimal IN-FORM version required: **2023.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "deleteAttachment",
                "security": [
                    {
                        "oAuth2": [
                            "api:attachments:delete"
                        ]
                    }
                ],
                "x-minInformVersion": "2023.00"
            }
        },
        "/companies/{company}/attachments/{key}/file": {
            "get": {
                "tags": [
                    "attachments"
                ],
                "summary": "getAttachmentFile",
                "description": "Used to get attachment file.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getAttachmentFile",
                "security": [
                    {
                        "oAuth2": [
                            "api:attachments:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2022.50"
            }
        },
        "/companies/{company}/attachmentsStructure/{resourceType}/resources/{resourceKey}": {
            "get": {
                "tags": [
                    "attachments"
                ],
                "summary": "getAttachmentsStructure",
                "description": "Used to get the directory structure of attachments in IN-FORM for a resource, that is specified using 'resourceType' and 'resourceKey'.<br><br>Minimal IN-FORM version required: **2024.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getAttachmentsStructure",
                "security": [
                    {
                        "oAuth2": [
                            "api:attachments:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2024.50"
            }
        },
        "/companies/{company}/attachmentsStructure/{resourceType}/resources/{resourceKey}/createDirectory": {
            "post": {
                "tags": [
                    "attachments"
                ],
                "summary": "createDirectoryInAttachmentsStructure",
                "description": "Used to create a directory in the structure of attachments in IN-FORM for a resource, that is specified using 'resourceType' and 'resourceKey'.<br><br>Minimal IN-FORM version required: **2024.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "createDirectoryInAttachmentsStructure",
                "security": [
                    {
                        "oAuth2": [
                            "api:attachments:write"
                        ]
                    }
                ],
                "x-minInformVersion": "2024.50"
            }
        },
        "/DbFindRecord": {
            "post": {
                "tags": [
                    "genTechPrototype"
                ],
                "summary": "DbFindRecord",
                "operationId": "DbFindRecord",
                "description": "!DO NOT USE! DbFindRecord<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "x-minInformVersion": "2022.50"
            }
        },
        "/DbSaveRecord": {
            "post": {
                "tags": [
                    "genTechPrototype"
                ],
                "summary": "DbSaveRecord",
                "operationId": "DbSaveRecord",
                "description": "!DO NOT USE! DbSaveRecord<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "x-minInformVersion": "2022.50"
            }
        },
        "/token": {
            "post": {
                "tags": [
                    "authorization"
                ],
                "security": [],
                "summary": "token",
                "description": "Used to grant access token, alongside with new refresh token.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "token",
                "x-minInformVersion": "2022.50"
            }
        },
        "/employees/{key}/changePassword": {
            "post": {
                "tags": [
                    "employees"
                ],
                "summary": "changePassword",
                "description": "Use this request to change password. When suceeded refresh token will become obsolete.<br>Please log in again using a new password and `/authorize` to get a new refresh token.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "changePassword",
                "x-minInformVersion": "2022.50"
            }
        },
        "/system/INFORMversion": {
            "get": {
                "tags": [
                    "system"
                ],
                "summary": "getINFORMVersion",
                "description": "Used to get client IN-FORM version.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getINFORMVersion",
                "x-minInformVersion": "2022.50"
            }
        },
        "/licenses/{license}/connected": {
            "get": {
                "security": [],
                "tags": [
                    "licenses"
                ],
                "summary": "isLicenseConnected",
                "description": "Used to check if can establish connection to IN-FORM with given license number. Can be used without authorization.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "isLicenseConnected",
                "x-minInformVersion": "2022.50"
            }
        },
        "/licenses/{license}/serverInfo": {
            "get": {
                "security": [],
                "x-minInformVersion": "2022.50",
                "tags": [
                    "licenses"
                ],
                "summary": "getServerInfo",
                "description": "Used to get information about server with given license. Can be used without authorization.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getServerInfo"
            }
        },
        "/api/details": {
            "get": {
                "tags": [
                    "documentation"
                ],
                "summary": "getOpenApi",
                "description": "Returns the document on which this documentation is based. Document follows OpenApi 2.0 specification<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getOpenApi",
                "x-minInformVersion": "2022.50"
            }
        },
        "/companies/{company}/addresses": {
            "get": {
                "tags": [
                    "addresses"
                ],
                "summary": "getAddresses",
                "description": "Used to get Address list.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getAddresses",
                "security": [
                    {
                        "oAuth2": [
                            "api:addresses:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2022.50"
            }
        },
        "/companies/{company}/addresses/{key}": {
            "get": {
                "tags": [
                    "addresses"
                ],
                "summary": "getAddress",
                "description": "Used to get Address data.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getAddress",
                "security": [
                    {
                        "oAuth2": [
                            "api:addresses:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2022.50"
            }
        },
        "/companies/{company}/addresses/{key}/binaryData/{field}": {
            "get": {
                "tags": [
                    "addresses"
                ],
                "summary": "getBinaryDataFromAddress",
                "description": "Use this endpoint to get efficiently the single, selected field, containing large data from specified address as binary data.<br>It works faster, than **getAddress** request.<br><br>Minimal IN-FORM version required: **2024.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getBinaryDataFromAddress",
                "security": [
                    {
                        "oAuth2": [
                            "api:addresses:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2024.00"
            }
        },
        "/companies/{company}/documents": {
            "post": {
                "tags": [
                    "documents"
                ],
                "summary": "postDocument",
                "description": "Used to create document in IN-FORM.<br><br>Minimal IN-FORM version required: **2023.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "postDocument",
                "security": [
                    {
                        "oAuth2": [
                            "api:documents:write"
                        ]
                    }
                ],
                "x-minInformVersion": "2023.50"
            },
            "get": {
                "tags": [
                    "documents"
                ],
                "summary": "getDocuments",
                "description": "Used to get list of Documents with informations their data.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getDocuments",
                "security": [
                    {
                        "oAuth2": [
                            "api:documents:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2022.50"
            }
        },
        "/companies/{company}/documents/{key}": {
            "get": {
                "tags": [
                    "documents"
                ],
                "summary": "getDocument",
                "description": "Used to get Document data.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getDocument",
                "security": [
                    {
                        "oAuth2": [
                            "api:documents:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2022.50"
            },
            "patch": {
                "tags": [
                    "documents"
                ],
                "summary": "patchDocument",
                "description": "Used to update document in IN-FORM.<br><br>Minimal IN-FORM version required: **2023.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "patchDocument",
                "security": [
                    {
                        "oAuth2": [
                            "api:documents:write"
                        ]
                    }
                ],
                "x-minInformVersion": "2023.50"
            }
        },
        "/companies/{company}/documents/{key}/binaryData/{field}": {
            "get": {
                "tags": [
                    "documents"
                ],
                "summary": "getBinaryDataFromDocument",
                "description": "Use this endpoint to get efficiently the single, selected field, containing large data from specified document as binary data.<br>It works faster, than **getDocument** request.<br><br>Minimal IN-FORM version required: **2024.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getBinaryDataFromDocument",
                "security": [
                    {
                        "oAuth2": [
                            "api:documents:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2024.00"
            }
        },
        "/companies/{company}/documents/{key}/workOrderForm": {
            "get": {
                "tags": [
                    "documents"
                ],
                "summary": "getWorkOrderForm",
                "description": "Used to get a work order form generated from a service document.<br><br>The work order form is generated automatically after setting the fitter and deadline in IN-FORM for service document. It contains a description that can be used to generate an editable view of the work order.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInfor[...]",
                "operationId": "getWorkOrderForm",
                "security": [
                    {
                        "oAuth2": [
                            "api:documents:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2022.50"
            },
            "patch": {
                "tags": [
                    "documents"
                ],
                "summary": "patchWorkOrderForm",
                "description": "Used to update a work order form generated from a service document.<br><br>The work order form is generated automatically after setting the fitter and deadline in IN-FORM for service document. It contains a description that can be used to generate an editable view of the work order.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minIn[...]",
                "operationId": "patchWorkOrderForm",
                "security": [
                    {
                        "oAuth2": [
                            "api:documents:write"
                        ]
                    }
                ],
                "x-minInformVersion": "2022.50"
            }
        },
        "/companies/{company}/documents/{key}/handleEmployeeAction": {
            "post": {
                "tags": [
                    "documents"
                ],
                "summary": "handleEmployeeAction",
                "description": "Command to change the realization state of a service document by an fitter. Use when the fitter reads, finishes, or rejects the service document. IN-FORM will save the note, and in case of rejection, send an e-mail.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "handleEmployeeAction",
                "security": [
                    {
                        "oAuth2": [
                            "api:documents:write"
                        ]
                    }
                ],
                "x-minInformVersion": "2022.50"
            }
        },
        "/companies/{company}/projects": {
            "get": {
                "tags": [
                    "projects"
                ],
                "summary": "getProjects",
                "description": "Used to get Projects list.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getProjects",
                "security": [
                    {
                        "oAuth2": [
                            "api:projects:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2022.50"
            }
        },
        "/companies/{company}/projects/{key}": {
            "get": {
                "tags": [
                    "projects"
                ],
                "summary": "getProject",
                "description": "Used to get Project data.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getProject",
                "security": [
                    {
                        "oAuth2": [
                            "api:projects:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2022.50"
            }
        },
        "/companies/{company}/projects/{key}/binaryData/{field}": {
            "get": {
                "tags": [
                    "projects"
                ],
                "summary": "getBinaryDataFromProject",
                "description": "Use this endpoint to get efficiently the single, selected field, containing large data from specified project as binary data.<br>It works faster, than **getProject** request.<br><br>Minimal IN-FORM version required: **2024.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getBinaryDataFromProject",
                "security": [
                    {
                        "oAuth2": [
                            "api:projects:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2024.00"
            }
        },
        "/companies/{company}/items": {
            "get": {
                "tags": [
                    "items"
                ],
                "summary": "getItems",
                "description": "Used to get list of Items with informations their data.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getItems",
                "security": [
                    {
                        "oAuth2": [
                            "api:items:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2022.50"
            }
        },
        "/companies/{company}/items/{key}": {
            "get": {
                "tags": [
                    "items"
                ],
                "summary": "getItem",
                "description": "Used to get Item data.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getItem",
                "security": [
                    {
                        "oAuth2": [
                            "api:items:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2022.50"
            }
        },
        "/companies/{company}/items/{key}/binaryData/{field}": {
            "get": {
                "tags": [
                    "items"
                ],
                "summary": "getBinaryDataFromItem",
                "description": "Use this endpoint to get efficiently the single, selected field, containing large data from specified item as binary data.<br>It works faster, than **getItem** request.<br><br>Minimal IN-FORM version required: **2024.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getBinaryDataFromItem",
                "security": [
                    {
                        "oAuth2": [
                            "api:items:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2024.00"
            }
        },
        "/companies/{company}/search": {
            "get": {
                "tags": [
                    "search"
                ],
                "summary": "search",
                "description": "Used to search data on many types of resources.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "search",
                "x-minInformVersion": "2022.50"
            }
        },
        "/companies/{company}/searchRecommended": {
            "get": {
                "tags": [
                    "search"
                ],
                "summary": "searchRecommended",
                "description": "Used to get many types of recommendation data from all resources for current user.<br><br>Minimal IN-FORM version required: **2023.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "searchRecommended",
                "x-minInformVersion": "2023.50"
            }
        },
        "/companies/{company}/servicedObjects": {
            "get": {
                "tags": [
                    "servicedObjects"
                ],
                "summary": "getServicedObjects",
                "description": "Used to get serviced objects list.<br><br>Minimal IN-FORM version required: **2023.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getServicedObjects",
                "security": [
                    {
                        "oAuth2": [
                            "api:servicedObjects:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2023.00"
            }
        },
        "/companies/{company}/servicedObjects/{key}": {
            "get": {
                "security": [
                    {
                        "oAuth2": [
                            "api:servicedObjects:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2022.50",
                "tags": [
                    "servicedObjects"
                ],
                "summary": "getServicedObject",
                "description": "Used to get serviced object data.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getServicedObject"
            }
        },
        "/companies/{company}/servicedObjects/{key}/binaryData/{field}": {
            "get": {
                "tags": [
                    "servicedObjects"
                ],
                "summary": "getBinaryDataFromServicedObject",
                "description": "Use this endpoint to get efficiently the single, selected field, containing large data from specified serviced object as binary data.<br>It works faster, than **getServicedObject** request.<br><br>Minimal IN-FORM version required: **2024.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getBinaryDataFromServicedObject",
                "security": [
                    {
                        "oAuth2": [
                            "api:servicedObjects:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2024.00"
            }
        },
        "/companies/{company}/settings/addresses": {
            "get": {
                "tags": [
                    "settings"
                ],
                "summary": "getAddressesSettings",
                "description": "This resource is used to obtain settings for addresses.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getAddressesSettings",
                "x-minInformVersion": "2022.50"
            }
        },
        "/companies/{company}/settings/contacts": {
            "get": {
                "tags": [
                    "settings"
                ],
                "summary": "getContactsSettings",
                "description": "This resource is used to obtain settings for contacts.<br><br>Minimal IN-FORM version required: **2025.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getContactsSettings",
                "x-minInformVersion": "2025.00"
            }
        },
        "/companies/{company}/settings/documents": {
            "get": {
                "x-minInformVersion": "2023.50",
                "tags": [
                    "settings"
                ],
                "summary": "getDocumentsSettings",
                "description": "Used to get settings for documents.<br><br>Minimal IN-FORM version required: **2023.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getDocumentsSettings"
            }
        },
        "/companies/{company}/settings/servicedObjects": {
            "get": {
                "x-minInformVersion": "2022.50",
                "tags": [
                    "settings"
                ],
                "summary": "getServiceSettings",
                "description": "Used to get settings for serviced objects.<br><br>Minimal IN-FORM version required: **2022.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getServiceSettings"
            }
        },
        "/companies/{company}/settings/timeTracking": {
            "get": {
                "x-minInformVersion": "2023.50",
                "tags": [
                    "settings"
                ],
                "summary": "getTimeTrackingSettings",
                "description": "Used to get settings for time tracking resources.<br><br>Minimal IN-FORM version required: **2023.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getTimeTrackingSettings"
            }
        },
        "/companies/{company}/loggedTimeTrackingEntries": {
            "post": {
                "tags": [
                    "timeTracking"
                ],
                "summary": "postLoggedTimeTrackingEntry",
                "description": "Used to create logged time tracking entry.<br><br>Minimal IN-FORM version required: **2023.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "postLoggedTimeTrackingEntry",
                "security": [
                    {
                        "oAuth2": [
                            "api:loggedTimeTrackingEntries:readWrite"
                        ]
                    }
                ],
                "x-minInformVersion": "2023.50"
            },
            "get": {
                "tags": [
                    "timeTracking"
                ],
                "summary": "getLoggedTimeTrackingEntries",
                "description": "Used to get logged time tracking entry list.<br><br>Minimal IN-FORM version required: **2023.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getLoggedTimeTrackingEntries",
                "security": [
                    {
                        "oAuth2": [
                            "api:loggedTimeTrackingEntries:readWrite"
                        ]
                    }
                ],
                "x-minInformVersion": "2023.50"
            }
        },
        "/companies/{company}/loggedTimeTrackingEntries/{key}": {
            "get": {
                "tags": [
                    "timeTracking"
                ],
                "summary": "getLoggedTimeTrackingEntry",
                "description": "Used to get logged time tracking entry's data.<br><br>Minimal IN-FORM version required: **2023.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getLoggedTimeTrackingEntry",
                "security": [
                    {
                        "oAuth2": [
                            "api:loggedTimeTrackingEntries:readWrite"
                        ]
                    }
                ],
                "x-minInformVersion": "2023.50"
            },
            "patch": {
                "tags": [
                    "timeTracking"
                ],
                "summary": "patchLoggedTimeTrackingEntry",
                "description": "Used for modification the informations about specified logged time tracking entry.<br><br>Minimal IN-FORM version required: **2023.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "patchLoggedTimeTrackingEntry",
                "security": [
                    {
                        "oAuth2": [
                            "api:loggedTimeTrackingEntries:readWrite"
                        ]
                    }
                ],
                "x-minInformVersion": "2023.50"
            },
            "delete": {
                "tags": [
                    "timeTracking"
                ],
                "summary": "deleteLoggedTimeTrackingEntry",
                "description": "Used to delete logged time tracking entry.<br><br>Minimal IN-FORM version required: **2023.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "deleteLoggedTimeTrackingEntry",
                "security": [
                    {
                        "oAuth2": [
                            "api:loggedTimeTrackingEntries:readWrite"
                        ]
                    }
                ],
                "x-minInformVersion": "2023.50"
            }
        },
        "/companies/{company}/timeTrackingEntryTemplates": {
            "post": {
                "tags": [
                    "timeTracking"
                ],
                "summary": "postTimeTrackingEntryTemplate",
                "description": "Used to create a new time tracking entry template.<br><br>Minimal IN-FORM version required: **2024.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "postTimeTrackingEntryTemplate",
                "security": [
                    {
                        "oAuth2": [
                            "api:loggedTimeTrackingEntries:readWrite"
                        ]
                    }
                ],
                "x-minInformVersion": "2024.50"
            },
            "get": {
                "tags": [
                    "timeTracking"
                ],
                "summary": "getTimeTrackingEntryTemplates",
                "description": "Used to get a list of the templates for time tracking entries.<br><br>Minimal IN-FORM version required: **2024.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getTimeTrackingEntryTemplates",
                "security": [
                    {
                        "oAuth2": [
                            "api:loggedTimeTrackingEntries:readWrite"
                        ]
                    }
                ],
                "x-minInformVersion": "2024.50"
            }
        },
        "/companies/{company}/timeTrackingEntryTemplates/{key}": {
            "get": {
                "tags": [
                    "timeTracking"
                ],
                "summary": "getTimeTrackingEntryTemplate",
                "description": "Used to get a specific template for time tracking entries.<br><br>Minimal IN-FORM version required: **2024.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getTimeTrackingEntryTemplate",
                "security": [
                    {
                        "oAuth2": [
                            "api:loggedTimeTrackingEntries:readWrite"
                        ]
                    }
                ],
                "x-minInformVersion": "2024.50"
            },
            "delete": {
                "tags": [
                    "timeTracking"
                ],
                "summary": "deleteTimeTrackingEntryTemplate",
                "description": "Used to delete a specific time tracking entry template.<br><br>Minimal IN-FORM version required: **2024.50**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "deleteTimeTrackingEntryTemplate",
                "security": [
                    {
                        "oAuth2": [
                            "api:loggedTimeTrackingEntries:readWrite"
                        ]
                    }
                ],
                "x-minInformVersion": "2024.50"
            }
        },
        "/companies/{company}/materialTrackingEntries": {
            "post": {
                "tags": [
                    "projects"
                ],
                "summary": "postMaterialTrackingEntry",
                "description": "Used to create material tracking entry.<br><br>Minimal IN-FORM version required: **2026.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "postMaterialTrackingEntry",
                "security": [
                    {
                        "oAuth2": [
                            "api:materialTrackingEntries:write"
                        ]
                    }
                ],
                "x-minInformVersion": "2026.00"
            },
            "get": {
                "tags": [
                    "projects"
                ],
                "summary": "getMaterialTrackingEntries",
                "description": "Used to get material tracking entries list.<br><br>Minimal IN-FORM version required: **2026.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getMaterialTrackingEntries",
                "security": [
                    {
                        "oAuth2": [
                            "api:materialTrackingEntries:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2026.00"
            }
        },
        "/companies/{company}/materialTrackingEntries/{key}": {
            "get": {
                "tags": [
                    "projects"
                ],
                "summary": "getMaterialTrackingEntry",
                "description": "Used to get material tracking entry's data.<br><br>Minimal IN-FORM version required: **2026.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getMaterialTrackingEntry",
                "security": [
                    {
                        "oAuth2": [
                            "api:materialTrackingEntries:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2026.00"
            },
            "patch": {
                "tags": [
                    "projects"
                ],
                "summary": "patchMaterialTrackingEntry",
                "description": "Used for modification of the information about a specific material tracking entry.<br><br>Minimal IN-FORM version required: **2026.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "patchMaterialTrackingEntry",
                "security": [
                    {
                        "oAuth2": [
                            "api:materialTrackingEntries:write"
                        ]
                    }
                ],
                "x-minInformVersion": "2026.00"
            },
            "delete": {
                "tags": [
                    "projects"
                ],
                "summary": "deleteMaterialTrackingEntry",
                "description": "Used to delete a material tracking entry.<br><br>Minimal IN-FORM version required: **2026.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "deleteMaterialTrackingEntry",
                "security": [
                    {
                        "oAuth2": [
                            "api:materialTrackingEntries:write"
                        ]
                    }
                ],
                "x-minInformVersion": "2026.00"
            }
        },
        "/companies/{company}/reports/projects/evaluation": {
            "get": {
                "tags": [
                    "projects"
                ],
                "summary": "getProjectEvaluationReport",
                "description": "Used to get information about project's financial state.<br><br>Minimal IN-FORM version required: **2026.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getProjectEvaluationReport",
                "security": [
                    {
                        "oAuth2": [
                            "api:projects:evaluation:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2026.00"
            }
        },
        "/companies/{company}/reports/projects/time": {
            "get": {
                "tags": [
                    "projects"
                ],
                "summary": "getProjectTimeReport",
                "description": "Used to get aggregated information about time tracking for the project.<br><br>Minimal IN-FORM version required: **2026.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getProjectTimeReport",
                "security": [
                    {
                        "oAuth2": [
                            "api:projects:evaluation:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2026.00"
            }
        },
        "/companies/{company}/reports/projects/material": {
            "get": {
                "tags": [
                    "projects"
                ],
                "summary": "getProjectMaterialReport",
                "description": "Used to get aggregated information about material for the project.<br><br>Minimal IN-FORM version required: **2026.00**.<br>When this is not met, then error will be returned.<br>Value of minimal IN-FORM version is available in the parameter: **x-minInformVersion** in openAPI.",
                "operationId": "getProjectMaterialReport",
                "security": [
                    {
                        "oAuth2": [
                            "api:projects:evaluation:read"
                        ]
                    }
                ],
                "x-minInformVersion": "2026.00"
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oAuth2": {
                "type": "oauth2",
                "description": "Authorization in IN-FORM API is oAuth2 password grant flow.<br>You need an `accessToken` to gain access. It can be obtained by sending a request POST `/token` with the `grantType` set as `password` and user credentials in the body of the request. The response also returns the expiry time of the `accessToken`. It needs to be obtained again after it expires.<br>Each request marked with `oAuth2` authorization requires adding an `accessToken` to the request header in [...]",
                "flows": {
                    "password": {
                        "tokenUrl": "https://api.in-software.com/v1/token",
                        "scopes": {
                            "api:access": "General access to IN-FORM API.",
                            "api:addresses:read": "Read access for general data of address.",
                            "api:addresses:write": "Write access for general data of address.",
                            "api:addresses:finance:read": "Read access for finance booking, terms of payment and bank details for address.",
                            "api:addresses:finance:write": "Write access for finance booking, terms of payment and bank details for address.",
                            "api:addresses:info:read": "Read access for info data of address.",
                            "api:addresses:info:write": "Write access for info data of address.",
                            "api:attachments:read": "Read access for attachments of other resources.",
                            "api:attachments:write": "Write access for attachments of other resources.",
                            "api:attachments:delete": "Delete access for attachments of other resources.",
                            "api:documents:read": "Read access for general data of document.",
                            "api:documents:write": "Write access for general data of document.",
                            "api:items:read": "Read access for general data of items.",
                            "api:items:write": "Write access for general data of items.",
                            "api:items:price:read": "Read access for price of item.",
                            "api:projects:read": "Read access for general data of project.",
                            "api:projects:write": "Write access for general data of project.",
                            "api:projects:evaluation:read": "Read access for evaluation data of project.",
                            "api:projects:evaluation:write": "Write access for evaluation data of project.",
                            "api:reports:read": "Read access for reports and statistics.",
                            "api:servicedObjects:read": "Read access for general data of serviced objects.",
                            "api:loggedTimeTrackingEntries:readWrite": "Read and write access for logged time tracking entries.",
                            "api:loggedTimeTrackingEntries:otherEmployees:readWrite": "Read and write access to create, edit and delete logged time tracking entries for other employees.",
                            "api:materialTrackingEntries:read": "Read access for material tracking entries.",
                            "api:materialTrackingEntries:write": "Write access for material tracking entries.",
                            "api:communicationSystem:readWrite": "Read and write access for communication system.",
                            "api:contacts:read": "Read access for general data of contacts.",
                            "api:contacts:write": "Write access for general data of contacts."
                        }
                    }
                }
            }
        }
    }
}